[versions]
agp = "8.13.1"
compiler = "5.0.5"
core = "1.17.0"
gson = "2.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
loggingInterceptor = "5.1.0"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
media = "1.7.1"
media3Exoplayer = "1.8.0"
okhttpVersion = "5.1.0"
overscrollDecorAndroid = "1.1.1"
paginate = "1.0.0"
palette = "1.0.0"
picasso = "2.71828"
roomRuntime = "2.8.3"
sdpAndroid = "1.1.1"
shimmer = "0.5.0"
slidingrootnav = "v1.1.1"
sspAndroid = "1.1.1"
swiperefreshlayout = "1.2.0-beta01"
jaudiotagger = "3.0.1"
googleGmsGoogleServices = "4.4.3"
firebaseAnalytics = "23.0.0"
firebaseMessaging = "25.0.1"

[libraries]
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
core = { module = "androidx.core:core", version.ref = "core" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
media = { module = "androidx.media:media", version.ref = "media" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
okhttp-v4120 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
overscroll-decor-android = { module = "io.github.everythingme:overscroll-decor-android", version.ref = "overscrollDecorAndroid" }
paginate = { module = "com.github.markomilos:paginate", version.ref = "paginate" }
palette = { module = "androidx.palette:palette", version.ref = "palette" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
slidingrootnav = { module = "com.github.yarolegovich:SlidingRootNav", version.ref = "slidingrootnav" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
jaudiotagger = { module = "net.jthink:jaudiotagger", version.ref = "jaudiotagger" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }

# Media3 Exoplayer related dependencies
[bundles]
media3Exoplayer = ["media3-exoplayer", "media3-ui", "media3-exoplayer-dash"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

